[project]
name = "sentry-options"
version = "0.0.0"
requires-python = ">=3.11"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.5.0",
    "sentry-devenv>=1.25.0",
]

[tool.mypy]
strict = true
