[package]
name = "sentry-options"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
sentry-options-validation.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
