[package]
name = "example"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
sentry-options = { path = "../../clients/rust" }
serde_json.workspace = true
anyhow.workspace = true
