name: main
permissions:
  contents: read

on:
  push:
    branches: [main, test-me-*, release/**]
    tags: '*'
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - {env: py312, python: '3.12'}
        - {env: py313, python: '3.13'}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: python -mpip install --upgrade setuptools tox virtualenv
    - run: tox -e ${{ matrix.env }}

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files
        id: changes
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        with:
          list-files: json
          filters: |
            all:
              - added|modified: '**/*'

      - uses: astral-sh/setup-uv@884ad927a57e558e7a70b92f2bccf9198a4be546 # v6
        with:
          version: '0.8.2'
          # we just cache the venv-dir directly in action-setup-venv
          enable-cache: false

      - uses: getsentry/action-setup-venv@5a9891716811c0f757b9a5d065a0bf022f2e813f # v3.1.0
        with:
          python-version: 3.14
          cache-dependency-path: uv.lock
          install-cmd: uv sync --frozen --active

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pre-commit
          key: cache-epoch-1|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml', 'uv.lock') }}

      - name: Install pre-commit
        run: pre-commit install-hooks

      - name: Run pre-commit
        run: |
          jq '.[]' --raw-output <<< '${{steps.changes.outputs.all_files}}' |
            # Run pre-commit to lint and format check files that were changed (but not deleted)
            xargs pre-commit run --files

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@884ad927a57e558e7a70b92f2bccf9198a4be546 # v6
      with:
        version: '0.8.2'
        enable-cache: false
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Rust Toolchain
      run: rustup toolchain install stable --profile minimal --no-self-update
    - run: |
        cd clients/python
        uv run --extra dev maturin build --release --out ../../dist/
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: dist/*

  rust-lint:
    name: Rust Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --component clippy --component rustfmt --no-self-update

      - uses: swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - name: Run Rustfmt
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --workspace --all-features --tests -- -D clippy::all

  rust-test:
    name: Rust Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          key: ${{ github.job }}

      - name: Run tests
        run: cargo test

  python-client-test:
    name: Python Client Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: astral-sh/setup-uv@884ad927a57e558e7a70b92f2bccf9198a4be546 # v6
        with:
          version: '0.8.2'
          enable-cache: false

      - uses: getsentry/action-setup-venv@5a9891716811c0f757b9a5d065a0bf022f2e813f # v3.1.0
        with:
          python-version: ${{ matrix.python }}
          cache-dependency-path: clients/python/uv.lock
          install-cmd: uv sync --frozen --extra dev --project clients/python
          working-directory: clients/python

      - uses: swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          key: ${{ github.job }}

      - name: Build extension
        working-directory: clients/python
        run: uv run maturin develop

      - name: Run tests
        working-directory: clients/python
        run: uv run pytest tests -xvs

  collector:
    needs: [build, pre-commit, tox, rust-lint, rust-test, python-client-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: check for failures
      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: echo 'dependent job failed' && exit 1
